

<style type="text/css">

#menu {
	background-color:black;
	color:white;
	padding:5px;
}

</style>

<ul class="nav nav-list">
  <li class="nav-header"><?php echo $this->studyName; ?></li>
  <li><a href="#">Participants</a></li>
  <li class="nav-header">Surveys</li>
  <?php foreach ($this->surveyNames as $surveyName) {
	echo '<li><a href="#">' . $surveyName . '</a></li>';
	}
	?>
</ul>
<!--  
<p>Study: 

</p>
&nbsp;&nbsp;&nbsp;<a>Select Participants</a><br><br>
Surveys:<br>
<?php foreach ($this->surveyNames as $surveyName) {
	echo '&nbsp;&nbsp;&nbsp;<a>' . $surveyName . '</a><br>';
}
?>-->
