<script type="text/javascript" src="jquery/jquery-1.7.2.js"></script>

<script type="text/javascript">
function onDelete(surveyName,surveyId){
		
	if (confirm("Are you sure you want to delete '" + surveyName + "'?") == true)
	{
		location.assign("/owner/surveylist/delete/" + surveyId);
	}
		
}

</script>

<style type="text/css">
.key {
	font-weight: bold;
}

.cell {
	padding: 10px;
}

</style>


<h2>My Surveys</h2>
<?php if (count($this->records)):?>
<div id="surveylist">
<table>
	<tr>
		<td></td>
		<td class="key" class="cell">Name</td>
		<td class="key" class="cell">Date Modified</td>
		<td class="key" class="cell">Date Created</td>
		<td></td>
	</tr>
	
	<?php foreach($this->records as $r): ?>
	<tr>
	<td></td>
	<td class="cell"><a href="<?php echo $this->url(array('surveyId' => $r["ID"]), 'owner-survey-show') ?> "><?php echo $this->escape($r['Name']);?> </a> </td>
	<td class="cell"><?php echo $this->escape($r['DateModified']);?> </td>
	<td class="cell"><?php echo $this->escape($r['DateCreated']);?> </td>
	<td class="cell"><input type="button" onclick="onDelete('<?php echo $this->escape($r['Name']) . "'," . $r['ID'];?>)" value="Delete" /></td>
	
	</tr>
	<?php endforeach; ?>

</table>

</div>
<?php endif; ?>