<script type="text/javascript" src="jquery/jquery-1.7.2.js"></script>

<script type="text/javascript">
function onDelete(studyName,studyId){
		
	if (confirm("Are you sure you want to delete '" + studyName + "'? This will delete all surveys and other data that it contains.") == true)
	{
		location.assign("/owner/studylist/delete/" + studyId);
	}
		
}

</script>

<style type="text/css">
.key {
	font-weight: bold;
}

.cell {
	padding: 10px;
}

</style>


<div class='row'>
	<div class='span5 offset1'><h2>My Studies</h2></div>
</div>
<br>

<?php if (count($this->records)):?>
<div class='row'>
<div class='span10 offset1' id="studylist">
<table class='table table-striped'>
	<tr>
		<td></td>
		<td class="key" class="cell">Name</td>
		<!-- <td class="key" class="cell">Date Modified</td>
		<td class="key" class="cell">Date Created</td> -->
		<td></td>
	</tr>
	
	<?php foreach($this->records as $r): ?>
	<tr>
	<td></td>
	<td class="cell"><a href="<?php echo $this->url(array('studyId' => $r["ID"]), 'owner-study-show') ?> "><?php echo $this->escape($r['Name']);?> </a> </td>
	<!-- <td class="cell"><?php echo $this->escape($r['DateModified']);?> </td>
	<td class="cell"><?php echo $this->escape($r['DateCreated']);?> </td> -->
	<td class="cell"><input type="button" onclick="onDelete('<?php echo $this->escape($r['Name']) . "'," . $r['ID'];?>)" value="Delete" /></td>
	
	</tr>
	<?php endforeach; ?>

</table>

</div>
</div>
<?php endif; ?>