<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<base href="/" />
    	<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/css/master.css">
		<?php echo $this->jQuery();  ?>
		<script type="text/javascript" src="/js/jquery/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="/js/Dialog.js"></script>
		<script type="text/javascript" src="/js/shared.js"></script>
	</head>
	<body> 
		<div id="header">
		<h1><img src="/img/logo.gif" /></h1>
			
			<div class="navbar">
	  			<div class="navbar-inner">
					<ul class="nav">
					  <li><a href="/owner/studylist/index">Home</a></li>
					  <li class="dropdown">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					      New
					      <b class="caret"></b>
					    </a>
					    <ul class="dropdown-menu">
					    	<li><a id='newStudy'><!--  href="#myModal" role="button" class="btn" data-toggle="modal"--> Study</a></li>
					    	<li><a id='newSurvey'><!--  href="#myModal" role="button" class="btn" data-toggle="modal"-->Survey</a></li></ul>
					  </li>
					</ul>
				</div>
			</div>
			
	    </div>
	    <div class='row-fluid'><div class='span11'>
	    <?php if (isset($this->studyName)): ?>
	    <ul class="nav nav-tabs pull-right">
		  <li class="active">
		    <a href="#">Design Survey</a>
		  </li>
		  <li><a href="#">Select Participants</a></li>
		  <li><a href="#">Analyze Results</a></li>
		</ul>
	    <?php endif; ?>
	    </div></div><br>
	    
    	<div class='row-fluid'>
    		<?php if (isset($this->studyName)) {// && isset($this->surveyNames)) { ?>
    			<div class='span2 offset1'>
    		
    			<?php echo $this->partial('partials/menu.phtml', 
                            array('studyName' => $this->studyName,
                            	'surveyNames' => $this->surveyNames)); ?>
                </div>
      			<div class='span8' id="content"><?php echo $this->layout()->content ?></div>
    	
    	<?php } else {
    		echo '<div class="span10 offset1" id="content">' . $this->layout()->content . '</div>';
    		
    	}?> 
      		
      	</div>
      	
<!--  
<div class="modal hide" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="myModalLabel"></h4>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Okay</button>
  </div>
</div>
-->
  	</body>
 </html>