<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<base href="/" />
		<link rel="stylesheet" type="text/css" href="/css/master.css" />
		<?php echo $this->jQuery();  ?>
		<script type="text/javascript" src="/js/jquery/js/jquery.cookie.js"></script>
	</head>
	<body> 
		<div id="header">
		<h1><img src="/img/logo.gif" /></h1>
		<table id="navPanel"><tr>
			<td class="navPanelLabel" id="mySurveys" onclick="location.assign('/owner/surveylist/index')">My Surveys</td>
			<td class="navPanelLabel" id="createSurvey" onclick="location.assign('/owner/surveylist/create')">Create Survey</td>
			<td id="navPanelEmpty"></td>
			<td class="navPanelLabel" id="logInOut">Log In</td>
		</tr></table>
	    </div>
	    <div'>
	    	<table style='width:90%'><tr>
	    		<td width='200px' id='menu'><?php echo $this->partial('partials/menu.phtml', 
                            array('studyName' => $this->studyName,
                            	'surveyNames' => $this->surveyNames)); ?>
                </td>
      			<td><div id="content"><?php echo $this->layout()->content ?></div> </td>
      		</tr></table>
    	</div> 
  	</body>
 </html>